config/routes.rb
Hobster::Application.routes.draw do

  resources :users
  resources :posts, :only => [:new, :create, :destroy, :show, :edit, :index]
  
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  match '/signout', :to => 'sessions#destroy'
  match '/profile', :to => 'pages#profile'
  match '/search', :to => 'posts#search'
  
  
  match "/user/:id", :as => 'new_profile', :to => 'users#show'

   root :to => "pages#home"

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider
  
  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end

  def self.create_from_hash(hash, user = nil)
    user ||= User.create_from_hash!(hash)
    Authorization.create(:user => user, :uid => hash['uid'], :provider => hash['provider'])
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :price, :city, :state, :address, :zip
  
  belongs_to :user
  
  validates_presence_of :title, :content, :price, :city, :state, :zip;
  validates :title, :length => { :maximum => 140 }
  validates :content, :length => { :maximum => 5000 }
  validates_format_of :price, :with => /^\d+(\.\d{0,2})?$/
  validates :state, :length => { :maximum => 2 }
  validates :zip, :length => { :is => 5 }
  validates_format_of :zip, :with => /^\d+{5}$/
  
  def self.search(search)
    if search
      find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations
  has_many :posts, :dependent => :destroy
  
  def self.create_from_hash!(hash)
    create(:name => hash['user_info']['name'])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def signed_in?
    !!current_user
  end

  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def home
  end
  
  def profile
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  # before_filter :authenticate
  
  def new
    @post = Post.new
    respond_to do |format|
      format.html
    end
  end
  
  def create
      @post = current_user.posts.build(params[:post])
        if @post.save
          redirect_to profile_path
        else
          render :action => 'new'
        end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes!(params[:post])
      flash[:success] = "post created!"
      render :action => 'show', :id => @post
    else 
      flash[:error] = "post not updated !!!"
      render :action => 'edit'
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def list
    
  end
  
  def destroy
    
  end
  
  def index
    @search = Post.search(params[:search])
    @posts = @search.all
  end
  
  def search
      @posts = Post.search(params[:search])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # render :text => request.env['omniauth.auth'].inspect
    auth = request.env['omniauth.auth']
    unless @auth = Authorization.find_from_hash(auth)
      # Create a new user or add an auth to existing user, depending on
      # whether there is already a user signed in.
      @auth = Authorization.create_from_hash(auth, current_user)
    end
    # Log the authorizing user in.
    self.current_user = @auth.user
    
    # render :text => "Welcome, #{current_user.name}."
    flash.now[:success] = "Welcome, #{current_user.name}."
    redirect_to root_path
  end
  
  def failure
    # render :text => "cannot connect to server! Please try again."
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = !params[:id].nil? ? User.find(params[:id]) : current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_authprovider.html.erb
<div class="auth_provider_group">
<p><strong> Sign in using </p>
<a href="/auth/twitter" class="auth_provider">
  <%= image_tag "twitter_32.png", :size => "32x32", :alt => "Twitter" %>
  
</a>
<a href="/auth/facebook" class="auth_provider">
  <%= image_tag "facebook_32.png", :size => "32x32", :alt => "Facebook" %>
  
</a>
</div>

app/views/layouts/_header.html.erb
<div class="topbar">
		  <div class="fill">
		    <div class="container">
		        <ul class="nav">
		          <li><%= link_to "Home", root_path %></li>
		          <li><a href="#about">About</a></li>
		          <% if current_user %>
		          	<li><%= link_to "Profile", profile_path %></li>
		          	<li><%= link_to "SignOut", signout_path, :method => :delete %></li>
		          <% end %>
		        </ul>
		        <% if current_user %>
		        <ul class="nav secondary-nav">
				  		<li><%= link_to current_user.name, new_profile_path(current_user.id) %></li>
				</ul>
		        <% end %>
		        <% if !current_user %>
					<ul class="nav secondary-nav">
				  		<li><a href="/auth/facebook">Facebook</a></li>
				  		<li><a href="/auth/twitter">Twitter</a></li>
					</ul>
				<% end %>
		    </div>
		  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hobster</title>
  <!-- <%= stylesheet_link_tag :all %> -->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <!--<%= stylesheet_link_tag 'custom', :media => 'screen' %>-->
  <!--<%= stylesheet_link_tag 'blueprint', :media => 'screen' %>-->
  <%= stylesheet_link_tag 'bootstrap.min', :media => 'screen' %>
</head>
<body>

	<%= render 'layouts/header' %>
	
	
	
		<%= yield %>
	<!--
	<div class="round">
		<% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
    </div>
   -->
	<%= debug params if Rails.env.development? %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<!-- <% if current_user %>
	<p> Welcome, <%= current_user.name %> </p>
	<%= link_to "Wanna Teach?", new_post_path, {:action => "new", :class => "create_button round" } %>	
<% end %>
<%= render 'shared/search_form' %>
-->
<div class="container">
			 <div class="hero-unit">
				<h1>Hobster</h1>
		          <p class="lead">
		           helps you find people in your locality who can teach you new and interesting hobbies<br />
		          </p>
		          <p><strong>Learn what you love!</strong>
		          <strong><%= link_to "Teach some thing today!", new_post_path %></strong></p>

		          
			</div>
			
			<%= render 'shared/search_form' %>
</div>

app/views/pages/profile.html.erb
<div class="container">
	<div class="hero-unit">
		<h1>My Profile</h1>
	</div>
<% if current_user.posts.count > 0 %>
		<!-- <p><h2>You have <%= current_user.posts.count %> posts.</h2></p> -->
		<% @posts = current_user.posts.all %>
		<% @posts.each do |post| %>
		<ul>
			<h3><%= link_to post.title, post_path(post.id), {:action => "show"} %></h3> 
			<!-- <%= link_to "edit", post_path(post.id), {:action => "edit"} %> | 
			<%= link_to "delete", post_path(:id) %> -->
		</ul>
		<% end %>
<% end %>
</div>

app/views/posts/edit.html.erb
<p> Edit posts here </p>

<%= render 'shared/edit_post_form' %>

app/views/posts/index.html.erb
<h2>Search results</h2>

<%= form_for @search do |f| %>
	<p>
		<%= f.text_field :title_contains %>
	</p>
	<p class = "button"> <%= f.submit %></p>
	
<% end %>

<% for post in @posts %>
	<h3><%= link_to post.title, post %></h3>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/post_form' %>

app/views/posts/search.html.erb
<div class="container">
	<div class="hero-unit">
		<h3>Search Results</h3>

<% if @posts %>
	<% for post in @posts %>
		<h3><%= link_to post.title, post %></h3>
		<%= link_to post.user.name, new_profile_path(post.user.id), {:action => "show"} %>
	<% end %>
<% else %>
	<h3>Sorry! No teachers could be found!</h3>
<% end %>

</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="hero-unit">
	
			<h2><%= @post.title %></h2> by <%= link_to @post.user.name, new_profile_path(@post.user.id) %>
	</div>
	
	<div class=span12>
			<h3>Location: 
				<% if @post.address %> <%= @post.address %>, <%end %> 
				<%= @post.city %>, <%= @post.state %> </h3>
			<p><strong><%= @post.content %></p>
				<% if @post.price.to_i > 0 %>
					<h3>$ <%= @post.price %> per lesson</h3>
				<% else %> <h3>Free!</h3>
				<% end %>
			<div id="map">
			<p>MAP<p>
			</div>
	</div>
	<% if current_user && current_user.id != @post.user.id %>
	<div class=span2>
		<%= link_to "REGISTER", html_options = { :class => "btn primary large" }
		 %>
	</div>
	<% end %>
</div>

app/views/shared/Copy of _search_form.html.erb
<%= form_tag search_path, :method => 'get', :url => { :action => "search" } do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :title => nil %>
	</p>
<% end %>

<%= form_tag search_path, :method => 'get', :url => { :action => "search" } do %>
					                    <div class="clearfix"> 
					                        <div class="input"> 
					                            <input class="xlarge" type="text" placeholder="Enter a hobby"/> 
					                        </div> 
					                    </div> 
					                    <div class="clearfix"> 
					                        <div class="input"> 
					                            <input type="text" placeholder="City,State or Zip"/> 
					                        </div> 
					                    </div> 
					                    <div class="actions"> 
					                        <button class="btn primary">Search</button> 
					                    </div> 
<% end %>

app/views/shared/_edit_post_form.html.erb
<%= form_for @post, :action => 'update', :id => @post, :html => { :class => "form_field" } do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div id="title_field">
  	Title<br>
    <%= f.text_field :title, :html => { :id => "title_fd"} %><br>
  </div>
  <div id="content_field">
    Content<br>
    <%= f.text_area :content %><br>
  </div>
  <div id="price_field">
    Price<br>
    <%= f.text_field :price %><br>
  </div>
  <div id="city_field">
    City<br>
    <%= f.text_field :city %><br>
  </div>
  <div id="state_field">
    State<br>
    <%= f.text_field :state %><br>
  </div>
  <div id="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/shared/_error.html.erb
<div class="alert-message warning">
    <p>Please login using Facebook to create a post!</p>
</div>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %></h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<div class="container">
	<div class="hero-unit">
		<h1>Create a teach post</h1>
	</div>		
</div>

<div class="container">
	<% if !current_user %>
	<%= render 'shared/error' %> <!-- please login before creating post message-->
	<% end %>
	
<%= simple_form_for @post do |f| %>
	<%= render 'shared/error_messages' %>
	<%= f.input :title %>
	<%= f.input :content, :as => :text, :input_html => { :rows => "4" } %>
	<%= f.input :price, :placeholder => "$", :hint => "price should be in USD, per lesson", :input_html => { :size => "6" } %> 
	<%= f.input :address %>
	<%= f.input :city %>
	<%= f.input :state %>
	<%= f.input :zip, :input_html => { :size => "5" } %>
	<%= f.submit 'Create'%>
<% end %>
</div>

app/views/shared/_search_form.html.erb
<%= form_tag search_path, :method => 'get', :url => { :action => "search" } do %>
	
	<%= text_field_tag :search, params[:search], :placeholder => "Enter a hobby"%>
	<%= text_field_tag :place, params[:place], :placeholder => "City, State or Zip"%>
	<%= submit_tag "Search", :title => nil, :id => "search_button" %>
	
<% end %>

app/views/users/show.html.erb
<div class="container">
	<div class="hero-unit">

		<h2> <%= @user.name %>'s Profile</h2>
	
		<% if @user.posts.count > 0 %>
			<% @posts = @user.posts.all %>
			<% @posts.each do |post| %>
			<ul>
				<h3><%= link_to post.title, post_path(post.id), {:action => "show"} %></h3> 
			<!-- <%= link_to "edit", post_path(post.id), {:action => "edit"} %> | 
			<%= link_to "delete", post_path(:id) %> -->
			</ul>
			<% end %>
		<% end %>
	</div>
</div>